export const defaultGamepadSettings = `[GCPad1]
Device = SDL/0/Steam Deck Controller
Buttons/A = \`Button E\`
Buttons/B = \`Button S\`
Buttons/X = \`Button N\`
Buttons/Y = \`Button W\`
Buttons/Z = Back
Buttons/Start = Start
Main Stick/Up = \`Left Y+\`
Main Stick/Down = \`Left Y-\`
Main Stick/Left = \`Left X-\`
Main Stick/Right = \`Left X+\`
Main Stick/Modifier = \`Shift\`
Main Stick/Calibration = 100.00 141.42 100.00 141.42 100.00 141.42 100.00 141.42
C-Stick/Up = \`Right Y+\`
C-Stick/Down = \`Right Y-\`
C-Stick/Left = \`Right X-\`
C-Stick/Right = \`Right X+\`
C-Stick/Modifier = \`Ctrl\`
C-Stick/Calibration = 100.00 141.42 100.00 141.42 100.00 141.42 100.00 141.42
Triggers/L = \`Shoulder L\`
Triggers/R = \`Shoulder R\`
D-Pad/Up = \`Pad N\`
D-Pad/Down = \`Pad S\`
D-Pad/Left = \`Pad W\`
D-Pad/Right = \`Pad E\`
Triggers/L-Analog = \`Trigger L\`
Triggers/R-Analog = \`Trigger R\`
Rumble/Motor = Weak
[GCPad2]
Device = evdev/0/Wireless Controller
Buttons/A = SOUTH
Buttons/B = EAST
Buttons/X = NORTH
Buttons/Y = WEST
Buttons/Start = START
D-Pad/Up = \`Axis 7-\`
D-Pad/Down = \`Axis 7+\`
D-Pad/Left = \`Axis 6-\`
D-Pad/Right = \`Axis 6+\`
Main Stick/Up = \`Axis 1-\`
Main Stick/Down = \`Axis 1+\`
Main Stick/Left = \`Axis 0-\`
Main Stick/Right = \`Axis 0+\`
Triggers/L = TL
Triggers/R = TR
Triggers/L-Analog = \`Full Axis 2+\`
Triggers/R-Analog = \`Full Axis 5+\`
[GCPad3]
Device = XInput2/0/Virtual core pointer
[GCPad4]
Device = XInput2/0/Virtual core pointer`;
