import { normalizeNewLines } from "../../configFile.js";

export const keyboardConfig =
  normalizeNewLines(`<?xml version="1.0" encoding="UTF-8"?>
<emulated_controller>
	<type>Wii U GamePad</type>
	<toggle_display>1</toggle_display>
	<controller>
		<api>Keyboard</api>
		<uuid>keyboard</uuid>
		<display_name>Keyboard</display_name>
		<axis>
			<deadzone>0.25</deadzone>
			<range>1</range>
		</axis>
		<rotation>
			<deadzone>0.25</deadzone>
			<range>1</range>
		</rotation>
		<trigger>
			<deadzone>0.25</deadzone>
			<range>1</range>
		</trigger>
		<mappings>
			<entry>
				<mapping>26</mapping>
				<button>65471</button>
			</entry>
			<entry>
				<mapping>14</mapping>
				<button>104</button>
			</entry>
			<entry>
				<mapping>13</mapping>
				<button>102</button>
			</entry>
			<entry>
				<mapping>12</mapping>
				<button>103</button>
			</entry>
			<entry>
				<mapping>11</mapping>
				<button>116</button>
			</entry>
			<entry>
				<mapping>24</mapping>
				<button>65363</button>
			</entry>
			<entry>
				<mapping>23</mapping>
				<button>65361</button>
			</entry>
			<entry>
				<mapping>22</mapping>
				<button>65364</button>
			</entry>
			<entry>
				<mapping>21</mapping>
				<button>65362</button>
			</entry>
			<entry>
				<mapping>16</mapping>
				<button>65506</button>
			</entry>
			<entry>
				<mapping>20</mapping>
				<button>100</button>
			</entry>
			<entry>
				<mapping>19</mapping>
				<button>97</button>
			</entry>
			<entry>
				<mapping>1</mapping>
				<button>107</button>
			</entry>
			<entry>
				<mapping>2</mapping>
				<button>106</button>
			</entry>
			<entry>
				<mapping>15</mapping>
				<button>120</button>
			</entry>
			<entry>
				<mapping>3</mapping>
				<button>105</button>
			</entry>
			<entry>
				<mapping>4</mapping>
				<button>117</button>
			</entry>
			<entry>
				<mapping>17</mapping>
				<button>119</button>
			</entry>
			<entry>
				<mapping>5</mapping>
				<button>108</button>
			</entry>
			<entry>
				<mapping>18</mapping>
				<button>115</button>
			</entry>
			<entry>
				<mapping>6</mapping>
				<button>111</button>
			</entry>
			<entry>
				<mapping>7</mapping>
				<button>56</button>
			</entry>
			<entry>
				<mapping>8</mapping>
				<button>57</button>
			</entry>
			<entry>
				<mapping>9</mapping>
				<button>65293</button>
			</entry>
			<entry>
				<mapping>10</mapping>
				<button>65288</button>
			</entry>
		</mappings>
	</controller>
</emulated_controller>`);
