import {
  globalDefaultInputConfigFileReset,
  type GlobalDefaultInputConfigFile,
} from "./config.js";

export const keyboardConfig: GlobalDefaultInputConfigFile = {
  ...globalDefaultInputConfigFileReset,
  "Player 1 Input": {
    Handler: "Keyboard",
    Device: "Keyboard",
    Config: {
      "Left Stick Left": "A",
      "Left Stick Down": "S",
      "Left Stick Right": "D",
      "Left Stick Up": "W",
      "Right Stick Left": "Left",
      "Right Stick Down": "Down",
      "Right Stick Right": "Right",
      "Right Stick Up": "Up",
      Start: "Return",
      Select: "Backspace",
      "PS Button": "",
      Square: "U",
      Cross: "J",
      Circle: "K",
      Triangle: "I",
      Left: "F",
      Down: "G",
      Right: "H",
      Up: "T",
      R1: "O",
      R2: "9",
      R3: "Shift Right",
      L1: "L",
      L2: "8",
      L3: "X",
      "IR Nose": "",
      "IR Tail": "",
      "IR Left": "",
      "IR Right": "",
      "Tilt Left": "",
      "Tilt Right": "",
      "Motion Sensor X": {
        Axis: "",
        Mirrored: false,
        Shift: 0,
      },
      "Motion Sensor Y": {
        Axis: "",
        Mirrored: false,
        Shift: 0,
      },
      "Motion Sensor Z": {
        Axis: "",
        Mirrored: false,
        Shift: 0,
      },
      "Motion Sensor G": {
        Axis: "",
        Mirrored: false,
        Shift: 0,
      },
      "Orientation Reset Button": "",
      "Orientation Enabled": false,
      "Pressure Intensity Button": "",
      "Pressure Intensity Percent": 50,
      "Pressure Intensity Toggle Mode": false,
      "Pressure Intensity Deadzone": 0,
      "Analog Limiter Button": "",
      "Analog Limiter Toggle Mode": false,
      "Left Stick Multiplier": 100,
      "Right Stick Multiplier": 100,
      "Left Stick Deadzone": 0,
      "Right Stick Deadzone": 0,
      "Left Stick Anti-Deadzone": 0,
      "Right Stick Anti-Deadzone": 0,
      "Left Trigger Threshold": 0,
      "Right Trigger Threshold": 0,
      "Left Pad Squircling Factor": 8000,
      "Right Pad Squircling Factor": 8000,
      "Color Value R": 0,
      "Color Value G": 0,
      "Color Value B": 0,
      "Blink LED when battery is below 20%": true,
      "Use LED as a battery indicator": false,
      "LED battery indicator brightness": 50,
      "Player LED enabled": true,
      "Large Vibration Motor Multiplier": 100,
      "Small Vibration Motor Multiplier": 100,
      "Switch Vibration Motors": false,
      "Mouse Movement Mode": "Relative",
      "Mouse Deadzone X Axis": 60,
      "Mouse Deadzone Y Axis": 60,
      "Mouse Acceleration X Axis": 200,
      "Mouse Acceleration Y Axis": 250,
      "Left Stick Lerp Factor": 100,
      "Right Stick Lerp Factor": 100,
      "Analog Button Lerp Factor": 100,
      "Trigger Lerp Factor": 100,
      "Device Class Type": 0,
      "Vendor ID": 1356,
      "Product ID": 616,
    },
    "Buddy Device": "",
  },
};
