import {
  playerInputReset,
  type GlobalDefaultInputConfigFile,
} from "./config.js";

export const keyboardConfig: GlobalDefaultInputConfigFile = {
  "Player 1 Input": {
    Handler: "Keyboard",
    Device: "Keyboard",
    Config: {
      "Left Stick Left": "A",
      "Left Stick Down": "S",
      "Left Stick Right": "D",
      "Left Stick Up": "W",
      "Right Stick Left": "Del",
      "Right Stick Down": "End",
      "Right Stick Right": "PgDown",
      "Right Stick Up": "Home",
      Start: "Return",
      Select: "Space",
      "PS Button": "Backspace",
      Square: "Z",
      Cross: "X",
      Circle: "C",
      Triangle: "V",
      Left: "Left",
      Down: "Down",
      Right: "Right",
      Up: "Up",
      R1: "E",
      R2: "T",
      R3: "G",
      L1: "Q",
      L2: "R",
      L3: "F",
      "IR Nose": "",
      "IR Tail": "",
      "IR Left": "",
      "IR Right": "",
      "Tilt Left": "",
      "Tilt Right": "",
      "Motion Sensor X": {
        Axis: "",
        Mirrored: false,
        Shift: 0,
      },
      "Motion Sensor Y": {
        Axis: "",
        Mirrored: false,
        Shift: 0,
      },
      "Motion Sensor Z": {
        Axis: "",
        Mirrored: false,
        Shift: 0,
      },
      "Motion Sensor G": {
        Axis: "",
        Mirrored: false,
        Shift: 0,
      },
      "Orientation Reset Button": "",
      "Orientation Enabled": false,
      "Pressure Intensity Button": "",
      "Pressure Intensity Percent": 50,
      "Pressure Intensity Toggle Mode": false,
      "Pressure Intensity Deadzone": 0,
      "Analog Limiter Button": "",
      "Analog Limiter Toggle Mode": false,
      "Left Stick Multiplier": 100,
      "Right Stick Multiplier": 100,
      "Left Stick Deadzone": 0,
      "Right Stick Deadzone": 0,
      "Left Stick Anti-Deadzone": 0,
      "Right Stick Anti-Deadzone": 0,
      "Left Trigger Threshold": 0,
      "Right Trigger Threshold": 0,
      "Left Pad Squircling Factor": 8000,
      "Right Pad Squircling Factor": 8000,
      "Color Value R": 0,
      "Color Value G": 0,
      "Color Value B": 0,
      "Blink LED when battery is below 20%": true,
      "Use LED as a battery indicator": false,
      "LED battery indicator brightness": 50,
      "Player LED enabled": true,
      "Large Vibration Motor Multiplier": 100,
      "Small Vibration Motor Multiplier": 100,
      "Switch Vibration Motors": false,
      "Mouse Movement Mode": "Relative",
      "Mouse Deadzone X Axis": 60,
      "Mouse Deadzone Y Axis": 60,
      "Mouse Acceleration X Axis": 200,
      "Mouse Acceleration Y Axis": 250,
      "Left Stick Lerp Factor": 100,
      "Right Stick Lerp Factor": 100,
      "Analog Button Lerp Factor": 100,
      "Trigger Lerp Factor": 100,
      "Device Class Type": 0,
      "Vendor ID": 1356,
      "Product ID": 616,
    },
    "Buddy Device": "",
  },
  "Player 2 Input": playerInputReset,
  "Player 3 Input": playerInputReset,
  "Player 4 Input": playerInputReset,
  "Player 5 Input": playerInputReset,
  "Player 6 Input": playerInputReset,
  "Player 7 Input": playerInputReset,
};
