import type { ParamToReplace } from "../../configFile";

export const keyboardConfig: ParamToReplace[] = [
  { keyValue: "profile=0" },
  { keyValue: "profile\\default=false" },
  { keyValue: 'profiles\\1\\button_a="code:75,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_a\\default=false" },
  { keyValue: 'profiles\\1\\button_b="code:74,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_b\\default=false" },
  { keyValue: 'profiles\\1\\button_debug="code:89,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_debug\\default=false" },
  { keyValue: 'profiles\\1\\button_down="code:71,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_down\\default=false" },
  { keyValue: 'profiles\\1\\button_gpio14="code:80,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_gpio14\\default=false" },
  { keyValue: 'profiles\\1\\button_home="code:69,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_home\\default=false" },
  { keyValue: 'profiles\\1\\button_l="code:76,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_l\\default=false" },
  { keyValue: 'profiles\\1\\button_left="code:70,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_left\\default=false" },
  { keyValue: 'profiles\\1\\button_power="code:86,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_power\\default=false" },
  { keyValue: 'profiles\\1\\button_r="code:79,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_r\\default=false" },
  { keyValue: 'profiles\\1\\button_right="code:72,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_right\\default=false" },
  { keyValue: 'profiles\\1\\button_select="code:16777219,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_select\\default=false" },
  { keyValue: 'profiles\\1\\button_start="code:16777220,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_start\\default=false" },
  { keyValue: 'profiles\\1\\button_up="code:84,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_up\\default=false" },
  { keyValue: 'profiles\\1\\button_x="code:73,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_x\\default=false" },
  { keyValue: 'profiles\\1\\button_y="code:85,engine:keyboard"' },
  { keyValue: "profiles\\1\\button_y\\default=false" },
  {
    keyValue:
      'profiles\\1\\button_zl="code:56,direction:+,engine:keyboard,threshold:0.5"',
  },
  { keyValue: "profiles\\1\\button_zl\\default=false" },
  {
    keyValue:
      'profiles\\1\\button_zr="code:57,direction:+,engine:keyboard,threshold:0.5"',
  },
  { keyValue: "profiles\\1\\button_zr\\default=false" },
  {
    keyValue:
      'profiles\\1\\c_stick="down:code$016777237$1engine$0keyboard,engine:analog_from_button,left:code$016777234$1engine$0keyboard,modifier:code$081$1engine$0keyboard,modifier_scale:0.500000,right:code$016777236$1engine$0keyboard,up:code$016777235$1engine$0keyboard"',
  },
  { keyValue: "profiles\\1\\c_stick\\default=false" },
  {
    keyValue:
      'profiles\\1\\circle_pad="down:code$083$1engine$0keyboard,engine:analog_from_button,left:code$065$1engine$0keyboard,modifier:code$081$1engine$0keyboard,modifier_scale:0.500000,right:code$068$1engine$0keyboard,up:code$087$1engine$0keyboard"',
  },
  { keyValue: "profiles\\1\\circle_pad\\default=false" },
  {
    keyValue:
      'profiles\\1\\motion_device="engine:motion_emu,update_period:100,sensitivity:0.01,tilt_clamp:90.0"',
  },
  { keyValue: "profiles\\1\\motion_device\\default=false" },
  { keyValue: "profiles\\1\\name\\default=false" },
  { keyValue: "profiles\\1\\touch_device=engine:emu_window" },
  { keyValue: "profiles\\1\\touch_device\\default=false" },
  { keyValue: "profiles\\1\\touch_from_button_map\\default=false" },
  { keyValue: "profiles\\1\\udp_input_address=127.0.0.1" },
  { keyValue: "profiles\\1\\udp_input_address\\default=false" },
  { keyValue: "profiles\\1\\udp_input_port=26760" },
  { keyValue: "profiles\\1\\udp_input_port\\default=false" },
  { keyValue: "profiles\\1\\udp_pad_index\\default=false" },
  { keyValue: "profiles\\1\\use_touch_from_button\\default=false" },
  { keyValue: "touch_from_button_maps\\1\\name\\default=false" },
  { keyValue: "use_artic_base_controller\\default=false" },
];
