import type { InputConfig } from "./config.js";

export const keyboardConfig: InputConfig = {
  left_joycon_stick: {
    stick_up: "W",
    stick_down: "S",
    stick_left: "A",
    stick_right: "D",
    stick_button: "X",
  },
  right_joycon_stick: {
    stick_up: "Up",
    stick_down: "Down",
    stick_left: "Left",
    stick_right: "Right",
    stick_button: "ShiftRight",
  },
  left_joycon: {
    button_minus: "BackSpace",
    button_l: "L",
    button_zl: "Number8",
    button_sl: "Unbound",
    button_sr: "Unbound",
    dpad_up: "T",
    dpad_down: "G",
    dpad_left: "F",
    dpad_right: "H",
  },
  right_joycon: {
    button_plus: "Enter",
    button_r: "O",
    button_zr: "Number9",
    button_sl: "Unbound",
    button_sr: "Unbound",
    button_x: "I",
    button_b: "J",
    button_y: "U",
    button_a: "K",
  },
  version: 1,
  backend: "WindowKeyboard",
  id: "0",
  controller_type: "ProController",
  player_index: "Player1",
};
