@startuml import categories
start
:read applications from user data;
:read foldernames in category folder;

' find categories for which applications are imported
while (more applications?)
  while (more categories?)
    if (application for category exists) then (yes)
      :read all files in the category folder (not recursive);
      :add data to valid categories;
    endif
  endwhile
endwhile

:delete categories;

while (valid categories?)
  :write category file;
  :write categories file;
endwhile
stop
@enduml