export type ApplicationId =
  | "duckstation"
  | "pcsx2"
  | "rpcs3"
  | "ppsspp"
  | "azahar"
  | "melonds"
  | "dolphin"
  | "ryujinx"
  | "cemu"
  | "mednafen"
  | "mame"
  | "ares"
  | "flycast"
  | "dosboxstaging"
  | "rosaliesMupenGui"
  | "scummvm"
  | "xemu";
