name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Preparing Container
        uses: pkgforge-dev/anylinux-setup-action@0964f2258d6c93d1391359978dde081fd8b3c6af # v2
      - name: Install Dependencies
        run: /bin/sh ./.github/scripts/get-dependencies.sh
      - name: Make AppImage
        run: /bin/sh ./.github/scripts/make-appimage.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: emuze-nightly.AppImage
          path: "dist/emuze*.AppImage"

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24.13.0"
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn app:distWindows --publish=never
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: emuze-Setup-nightly.exe
          path: "dist/emuze*.exe"
