// TODO: find new name to not collide with igdbPlatformIds
export type PlatformId =
  | "sonyplaystation"
  | "sonyplaystation2"
  | "sonyplaystation3"
  | "sonypsp"
  | "segamastersystem"
  | "segamegadrive"
  | "segacd"
  | "segadreamcast"
  | "supernintendo"
  | "nintendods"
  | "nintendo3ds"
  | "nintendogamecube"
  | "arcade"
  | "nintendowii"
  | "nintendoentertainmentsystem"
  | "nintendo64"
  | "nintendogameboy"
  | "nintendogameboycolor"
  | "nintendogameboyadvance"
  | "segasaturn"
  | "pcengine"
  | "pcenginecd"
  | "neogeo"
  | "neogeocd";
